# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cb9243b1eb1f3a6e08b8d62ccbc295b104e626c03cfa544abbe19f97125c2b02badb1140ac426d9d6fd54cc05be5ec2d11bab1a56c8897aa42439da008bef8c

test:
  secret_key_base: e38861aa3779e9811e048a12802e2fd149cc8dbe7f341a4f7c18e97311378489c0c1a39cd7138ecc3392e5eac61cd350b8284c194b18961b9a6b675d3f0f8292

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
